In [17]:
#import PIL
import cv2
import tensorflow as tf
import numpy as np
import os

In [18]:
#PIL Import
#images = [PIL.Image.open('pics/'+x) for x in os.listdir('pics/')]
images = [cv2.imread('pics/'+x) for x in os.listdir('pics/')]

In [1]:
class compressable_image:
    def __init__(self, image):
        
        self.M = len(image)
        self.N = len(image[0])
        self.unrolled_image = self.unroll_image(image)
        self.image = []
        
    def unroll_image(self, original_image):
        new_image = []
        for i, row in enumerate(original_image):
            for j, pixel in enumerate(row):
                new_image.append(pixel)
        return new_image
    
    def k_means_compression(self, K=16):
        
        # ||x-mu||**2
        euclidean_distance = lambda x: np.inner(x,x)
        
        centroids = [np.random.randint(255, size=(1, 3)) for _ in range(K)]
        last = {}
        changed = True
        while changed:
            changed = False
            assignments = [[] for _ in range(K)]
            for i, pixel in enumerate(self.unrolled_image):
                assigned_k = min([(euclidean_distance(pixel-centroids[k]), k) for k in range(K)])[1]
                assignments[assigned_k].append(pixel)
                if i not in last or last[i] != assigned_k:
                    changed = True
                last[i] = assigned_k
                
            for i, assignment in enumerate(assignments):
                new_centroid = np.sum(assignment, axis = 0)/len(assignment)
                centroids[i] = new_centroid

        for pixel in last:
            self.unrolled_image[pixel] = centroids[last[pixel]]

        self.reroll_image()
        
    def reroll_image(self):
        
        self.image = np.zeros((self.M,self.N,3))
        ind = 0
        for i in range(self.M):
            for j in range(self.N):
                for d in range(3):
                    self.image[i][j][d] = self.unrolled_image[ind][d]
                ind += 1
            
        

In [78]:
unrolled_images = [compressable_image(x) for x in images[:1]]

In [79]:
unrolled_images[0].k_means_compression()

KeyboardInterrupt: 

In [80]:
centroids = [np.random.randint(255, size=(1, 3)) for _ in range(5)]

In [81]:
centroids

[array([[ 76, 195, 136]]),
 array([[167, 165, 132]]),
 array([[178,  14, 167]]),
 array([[ 55, 122,  65]]),
 array([[173, 191,  64]])]

In [82]:
np.sum(centroids, axis = 0)/len(centroids)

array([[129.8, 137.4, 112.8]])

In [125]:
testimg = cv2.imread('pics/test.png')

In [129]:
test = compressable_image(testimg)

In [130]:
test.k_means_compression()

In [135]:
test.image
img = cv2.imwrite('test_img.jpg', test.image)
cv2.imshow("image", img)
cv2.waitKey()

32

In [114]:
a =np.array([])

In [115]:
np.append(a,5)
a

array([], dtype=float64)

In [116]:
a = np.append(a,5)

In [117]:
a

array([5.])

In [118]:
a = np.append(a,np.array)

In [119]:
a

array([5.0, <built-in function array>], dtype=object)