In [17]:
#import PIL
import cv2
import tensorflow as tf
import numpy as np
import os

In [23]:
#PIL Import
#images = [PIL.Image.open('pics/'+x) for x in os.listdir('pics/')]
images = [cv2.imread('pics/'+x) for x in os.listdir('pics/')]

(768, 1024, 3)
(1024, 834, 3)
(768, 1024, 3)
(1024, 768, 3)
(1024, 768, 3)
(1024, 768, 3)
(1024, 768, 3)
(886, 886, 3)
(768, 1024, 3)
(768, 1024, 3)
(768, 1024, 3)
(1024, 768, 3)
(768, 1024, 3)
(1024, 768, 3)
(1024, 768, 3)


In [29]:
class compressable_image:
    def __init__(self, image):
        
        self.M = len(image)
        self.N = len(image[0])
        self.unrolled_image = self.unroll_image(image)
        
    def unroll_image(self, original_image):
        new_image = []
        for i, row in enumerate(original_image):
            for j, pixel in enumerate(row):
                new_image.append(pixel)
        return new_image

In [30]:
unrolled_images = [compressable_image(x).unrolled_image for x in images]

In [31]:
unrolled_images[0]

[array([223, 213, 213], dtype=uint8),
 array([223, 213, 213], dtype=uint8),
 array([223, 213, 213], dtype=uint8),
 array([220, 211, 208], dtype=uint8),
 array([217, 208, 205], dtype=uint8),
 array([216, 204, 202], dtype=uint8),
 array([212, 200, 198], dtype=uint8),
 array([208, 196, 194], dtype=uint8),
 array([209, 196, 194], dtype=uint8),
 array([208, 195, 193], dtype=uint8),
 array([206, 193, 191], dtype=uint8),
 array([203, 191, 187], dtype=uint8),
 array([202, 190, 186], dtype=uint8),
 array([205, 190, 187], dtype=uint8),
 array([204, 189, 186], dtype=uint8),
 array([202, 187, 184], dtype=uint8),
 array([203, 191, 185], dtype=uint8),
 array([203, 191, 185], dtype=uint8),
 array([204, 192, 186], dtype=uint8),
 array([205, 191, 185], dtype=uint8),
 array([204, 190, 184], dtype=uint8),
 array([204, 189, 186], dtype=uint8),
 array([205, 190, 187], dtype=uint8),
 array([208, 191, 188], dtype=uint8),
 array([209, 192, 189], dtype=uint8),
 array([209, 192, 189], dtype=uint8),
 array([210,